[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"
  DATABASE_URL = "file:./dev.db"
  DEV_MODE_OTP = "true"
  JWT_SECRET = "advora_super_secure_jwt_secret_key_2026"

[functions]
  included_files = ["prisma/**"]

[[plugins]]
  package = "@netlify/plugin-nextjs"

